name = "RFFT"
uuid = "3bd9afcd-55df-531a-9b34-dc642dce7b95"
authors = ["Tim Holy <tim.holy@gmail.com>"]
version = "0.0.0"

[deps]
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
